coverage:
  ignore:
    - "examples/.*"
    - "src/maicos/_version.py"
    - "tests/.*"
    - "versioneer.py"
  status:
    project:
      default:
        target: 90%
    patch: false

comment: false
