default:
  before_script:
  - apt-get update -q -y
  - apt-get -y install python3-dev python3-pip
  - pip3 install -r requirements.txt
  - export USE_CYTHON=True

stages:
  - test
  - deploy
  - release

test:
  image: python:3.7
  stage: test
  script:
    - pip3 install --upgrade pip setuptools wheel
    - python setup.py build_ext --inplace
    - pip3 install sphinx sphinx-press-theme
    - sphinx-build -b html docs/source public
    - pip3 install .
    - cd tests
    - pytest --disable-pytest-warnings .

deploy:
  image: python:3.7
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip3 install twine
    - python3 setup.py sdist
    - twine upload dist/*
  only:
    - master

pages:
  image: python:3.7
  stage: release
  script:
  - pip3 install --upgrade pip setuptools wheel
  - python setup.py build_ext --inplace
  - pip3 install sphinx sphinx-press-theme
  - sphinx-build -b html docs/source public
  artifacts:
    paths:
    - public
  only:
  - develop




