default:
  image: python:3.10
  before_script:
    - python -m pip install -U tox
    - export USE_CYTHON=True

.matrix:
  image: python:$PYTHON_VERSION
  needs: []
  parallel:
    matrix:
      - PYTHON_VERSION: ['3.8', '3.9', '3.10']

stages:
  - lint
  - build
  - docs
  - tests
  - deploy

###########################
######### LINT ############
###########################

lint:
  stage: lint
  needs: []
  script:
    - tox -e lint

###########################
######### BUILD ###########
###########################

build:
  extends: .matrix
  stage: build
  script:
    - tox -e build
  artifacts:
    paths:
      - dist
    expire_in: 1 week


###########################
######### DOCS ############
###########################

docs:
  stage: docs
  needs: []
  script:
    - apt-get update -q -y
    - apt-get -y install pandoc gnuplot
    - tox -e docs
  artifacts:
    paths:
      - dist/docs

###########################
######### TESTS ###########
###########################

tests:
  extends: .matrix
  stage: tests
  variables:
    CODECOV_TOKEN: $CODECOV_TOKEN
  script:
    - tox -e tests
  after_script:
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov -t $CODECOV_TOKEN

###########################
######## DEPLOY ###########
###########################

# The name must be `pages`!
# Otherwise webpage on gitlab.io will not be updated!
pages:
  stage: deploy
  script:
    - cp -r dist/docs public
  only:
    - tags
  artifacts:
    paths:
      - public

pypi:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install twine
    - twine upload --verbose dist/*.tar.gz dist/*.whl
  only:
    - tags
