default:
  before_script:
    - python -m pip install -U tox
    - export USE_CYTHON=True

stages:
  - lint
  - build
  - tests
  - deploy

###########################
######### LINT ############
###########################

.lint:
  stage: lint
  needs: []
  script:
    - tox -e lint

lint:3.8:
  image: python:3.8
  extends: .lint

lint:3.9:
  image: python:3.9
  extends: .lint

lint:3.10:
  image: python:3.10
  extends: .lint

###########################
######### BUILD ###########
###########################

.build:
  stage: build
  needs: []
  script:
    - tox -e build
  artifacts:
    paths:
      - dist

build:3.8:
  image: python:3.8
  extends: .build

build:3.9:
  image: python:3.9
  extends: .build

build:3.10:
  image: python:3.10
  extends: .build

build:docs:
  image: python:3.10
  stage: build
  needs: []
  script:
    - apt-get update -q -y
    - apt-get -y install pandoc
    - tox -e docs
  artifacts:
    paths:
      - dist/docs

###########################
######### TESTS ###########
###########################

.tests:
  stage: tests
  needs: []
  variables:
    CODECOV_TOKEN: $CODECOV_TOKEN
  script:
    - tox -e tests
  after_script:
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov -t $CODECOV_TOKEN

tests:3.8:
  image: python:3.8
  extends: .tests

tests:3.9:
  image: python:3.9
  extends: .tests

tests:3.10:
  image: python:3.10
  extends: .tests

###########################
######## DEPLOY ###########
###########################

# The name must be `pages`!
# Otherwise webpage on gitlab.io will not be updated!
pages:
  image: python:3.10
  stage: deploy
  script:
    - cp -r dist/docs public
  only:
    - tags
  artifacts:
    paths:
      - public

pypi:
  image: python:3.10
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install twine
    - twine upload --verbose dist/*.tar.gz dist/*.whl
  only:
    - tags
