default:
  before_script:
    - apt-get update -q -y
    - apt-get -y install python3-dev python3-pip texlive-base texlive-fonts-recommended texlive-fonts-extra dvipng cm-super
    - pip install tox
    - export USE_CYTHON=True

stages:
  - lint
  - build
  - docs
  - tests
  - deploy

###########################
######### LINT ############
###########################

.lint:
  stage: lint
  needs: []
  allow_failure: True
  script:
    - tox -e lint

lint:3.7:
  image: python:3.7
  extends: .lint

lint:3.8:
  image: python:3.8
  extends: .lint

lint:3.9:
  image: python:3.9
  extends: .lint

lint:3.10:
  image: python:3.10
  extends: .lint

###########################
######### BUILD ###########
###########################

.build:
  stage: build
  needs: []
  script:
    - tox -e build
  artifacts:
    paths:
      - dist

build:3.7:
  image: python:3.7
  extends: .build

build:3.8:
  image: python:3.8
  extends: .build

build:3.9:
  image: python:3.9
  extends: .build

build:3.10:
  image: python:3.10
  extends: .build

###########################
######### DOCS ############
###########################

docs:
  image: python:3.9
  stage: docs
  needs: []
  script: tox -e docs
  after_script:
    - cp -r dist/docs public  # GitLab pages want their data at 'public'
  artifacts:
    paths:
      - public

###########################
######### TESTS ###########
###########################

.tests:
  stage: tests
  needs: []
  variables:
    CODECOV_TOKEN: $CODECOV_TOKEN
  script:
    - tox -e tests
  after_script:
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov -t $CODECOV_TOKEN

tests:3.7:
  image: python:3.7
  extends: .tests

tests:3.8:
  image: python:3.8
  extends: .tests

tests:3.9:
  image: python:3.9
  extends: .tests

tests:3.10:
  image: python:3.10
  extends: .tests

###########################
######## DEPLOY ###########
###########################

deploy:
  image: python:3.10
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload --verbose dist/*
  only:
    - master
