codecov:
  bot: secret:v2::zGmughu9NJ45YJ7kSJq8EXwWijtalWaIRsPR8XVj7gT2NNTWz6ulWRhtiEVHmTOBbtcQsTfJHI82SKAq3rfRaA==

coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 2%

comment:
  show_critical_paths: true

profiling:
  critical_files_paths:
    - src/maicos/core/*
    - src/maicos/lib/*
